using OPUPMS.Domain.Base;
using OPUPMS.Domain.Hotel.Model.ConvertModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;

namespace OPUPMS.Domain.Hotel.Model
{
    public class HotelConvertModelProfile : Profile // : BaseConvertModelProfile
    {
        public HotelConvertModelProfile() // : base()
        {
            //配置AutoMapper
            #region 房号代码对象映射
            CreateMap<FhdmModel, RoomSymbolInfo>()
                    .ForMember(dest => dest.RoomNo, opt => opt.MapFrom(src => src.Id.Trim()))
                    .ForMember(dest => dest.RoomState, opt => opt.MapFrom(src => src.Fhdmft00.Trim()))
                    .ForMember(dest => dest.FloorCode, opt => opt.MapFrom(src => src.Fhdmlc00.Trim()))
                    .ForMember(dest => dest.GalleryCode, opt => opt.MapFrom(src => src.Fhdmlz00.Trim()))
                    .ForMember(dest => dest.IsClean, opt => opt.MapFrom(src => src.Fhdmcd00.Trim().ToUpper()))
                    .ForMember(dest => dest.OtherStatus, opt => opt.MapFrom(src => src.Fhdmqtzt))
                    .ForMember(dest => dest.RoomTypeCode, opt => opt.MapFrom(src => src.Fhdmlx00.Trim()))
                    .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Fhdmdj00))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Fhdmzt00))
                    .ForMember(dest => dest.Status01, opt => opt.MapFrom(src => src.Fhdmzt01))
                    .ForMember(dest => dest.Status02, opt => opt.MapFrom(src => src.Fhdmzt02))
                    .ForMember(dest => dest.ActualStayGuests, opt => opt.MapFrom(src => src.Fhdmszrs))
                    .ForMember(dest => dest.AllowStayGuests, opt => opt.MapFrom(src => src.Fhdmkzrs))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Fhdmbz00))
                    .ReverseMap();  //反向映射 
            #endregion

            #region 房间事务对象映射
            //配置AutoMapper
            CreateMap<FhswModel, RoomRoutineInfo>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.AccountingDate, opt => opt.MapFrom(src => src.Fhswzwrq))
                .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.Fhswzzrq))
                .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Fhswczsj))
                .ForMember(dest => dest.ReasonCode, opt => opt.MapFrom(src => src.Fhswyydm.Trim().ToUpper()))
                .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Fhswbz00))
                .ForMember(dest => dest.RoomNo, opt => opt.MapFrom(src => src.Fhswfh00))
                .ForMember(dest => dest.RoutineCode, opt => opt.MapFrom(src => src.Fhswswdm.Trim().ToUpper()))
                .ForMember(dest => dest.RoutineState, opt => opt.MapFrom(src => src.Fhswbzs0.Trim().ToUpper()))
                .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.Fhswksrq))
                .ForMember(dest => dest.SubmitDate, opt => opt.MapFrom(src => src.Fhswtjrq))
                .ForMember(dest => dest.SubmitTime, opt => opt.MapFrom(src => src.Fhswtjsj))
                .ForMember(dest => dest.SubmitUser, opt => opt.MapFrom(src => src.Fhswtjcz))
                .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Fhswczdm))
                .ReverseMap();  //反向映射 
            #endregion

            #region 客人资料对象映射
            CreateMap<KrzlModel, GuestDataInfo>()//创建映射
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))//指定映射属性
                    .ForMember(dest => dest.AccountType, opt => opt.MapFrom(src => src.Krzlzhlx))
                    .ForMember(dest => dest.Address, opt => opt.MapFrom(src => src.Krzldz00))
                    .ForMember(dest => dest.AccRemark, opt => opt.MapFrom(src => src.Krzlzwbz))
                    .ForMember(dest => dest.BookingId, opt => opt.MapFrom(src => src.Krzlydh0))
                    .ForMember(dest => dest.BookingDetailId, opt => opt.MapFrom(src => src.Krzldfmx))
                    .ForMember(dest => dest.CardNo, opt => opt.MapFrom(src => src.Krzlkh00))
                    .ForMember(dest => dest.ClientSourceCode, opt => opt.MapFrom(src => src.Krzlscdm))
                    .ForMember(dest => dest.CheckInDate, opt => opt.MapFrom(src => src.Krzlrzrq))
                    .ForMember(dest => dest.CheckInTime, opt => opt.MapFrom(src => src.Krzlrzsj))
                    .ForMember(dest => dest.CheckOutDate, opt => opt.MapFrom(src => src.Krzlldrq))
                    .ForMember(dest => dest.CheckOutTime, opt => opt.MapFrom(src => src.Krzlldsj))
                    .ForMember(dest => dest.ChineseName, opt => opt.MapFrom(src => src.Krzlzwxm))
                    .ForMember(dest => dest.ChummageId, opt => opt.MapFrom(src => src.Krzltzxh))
                    .ForMember(dest => dest.CountryCode, opt => opt.MapFrom(src => src.Krzlgj00))
                    .ForMember(dest => dest.ConsumeAmount, opt => opt.MapFrom(src => src.Krzlxfze))
                    .ForMember(dest => dest.CustomerType, opt => opt.MapFrom(src => src.Krzllxdm))
                    .ForMember(dest => dest.CredentialCategory, opt => opt.MapFrom(src => src.Krzlzjlb))
                    .ForMember(dest => dest.CredentialNo, opt => opt.MapFrom(src => src.Krzlzjhm))
                    .ForMember(dest => dest.CurrencyType, opt => opt.MapFrom(src => src.Krzljzhb.Trim().ToUpper()))
                    .ForMember(dest => dest.EnglishName, opt => opt.MapFrom(src => src.Krzlywxm))
                    .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Krzlmail))
                    .ForMember(dest => dest.GuestCategory, opt => opt.MapFrom(src => src.Krzlkrlb.Trim().ToUpper()))
                    .ForMember(dest => dest.GuestRemark, opt => opt.MapFrom(src => src.Krzlkrbz))
                    .ForMember(dest => dest.GuestType, opt => opt.MapFrom(src => src.Krzlkrlx.Trim().ToUpper()))
                    .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Krzlxb00))
                    .ForMember(dest => dest.VipType, opt => opt.MapFrom(src => src.Krzlvip0))
                    .ForMember(dest => dest.LinkRoomId, opt => opt.MapFrom(src => src.Krzltlxh))
                    .ForMember(dest => dest.NativePlaceCode, opt => opt.MapFrom(src => src.Krzljg00))
                    .ForMember(dest => dest.PayBillId, opt => opt.MapFrom(src => src.Krzljzzh))
                    .ForMember(dest => dest.PayBillMethod, opt => opt.MapFrom(src => src.Krzljzfs.Trim().ToUpper()))
                    .ForMember(dest => dest.PeopleCategory, opt => opt.MapFrom(src => src.Krzlmz00))
                    .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Krzldh00))
                    .ForMember(dest => dest.RemainAmount, opt => opt.MapFrom(src => src.Krzlye00))
                    .ForMember(dest => dest.RoomFullPrice, opt => opt.MapFrom(src => src.Krzlfqj0))
                    .ForMember(dest => dest.RoomRemark, opt => opt.MapFrom(src => src.Krzlfwbz))
                    .ForMember(dest => dest.RoomRent, opt => opt.MapFrom(src => src.Krzlfz00))
                    .ForMember(dest => dest.RoomNo, opt => opt.MapFrom(src => src.Krzlfh00.Trim()))
                    .ForMember(dest => dest.RoomPriceCategory, opt => opt.MapFrom(src => src.Krzlfjlb.Trim().ToUpper()))
                    .ForMember(dest => dest.RoomType, opt => opt.MapFrom(src => src.Krzlfjlx.Trim().ToUpper()))
                    .ForMember(dest => dest.SellerCode, opt => opt.MapFrom(src => src.Krzlywy0))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Krzlzt00))
                    .ForMember(dest => dest.SpecialServices, opt => opt.MapFrom(src => src.Krzltf00))
                    //.ForMember(dest => dest.DiscountRate, opt => opt.MapFrom(src => src.Krzlyhl0))
                    .ForMember(dest => dest.TeamName, opt => opt.MapFrom(src => src.Krzltm00))
                    .ForMember(dest => dest.TeamNo, opt => opt.MapFrom(src => src.Krzlth00))
                    .ForMember(dest => dest.ApprovePriceUser, opt => opt.MapFrom(src => src.Krzlfjpz))
                    .ForMember(dest => dest.AuthorizeAmount, opt => opt.MapFrom(src => src.Krzlsqje))
                    .ForMember(dest => dest.BirthDate, opt => opt.MapFrom(src => src.Krzlcsrq))
                    .ForMember(dest => dest.ChargeLimitAmount, opt => opt.MapFrom(src => src.Krzlgzxe))
                    .ForMember(dest => dest.ChargeLimitFlag, opt => opt.MapFrom(src => src.Krzlgzbz))
                    .ForMember(dest => dest.ChargeLimitId, opt => opt.MapFrom(src => src.Krzlgzxh))
                    .ForMember(dest => dest.Company, opt => opt.MapFrom(src => src.Krzlgs00))
                    .ForMember(dest => dest.EnglishName01, opt => opt.MapFrom(src => src.Krzlywx1))
                    .ForMember(dest => dest.ExtendStayDate, opt => opt.MapFrom(src => src.Krzlxzrq))
                    .ForMember(dest => dest.Fax, opt => opt.MapFrom(src => src.Krzlfax0))
                    .ForMember(dest => dest.ForeignerDetailId, opt => opt.MapFrom(src => src.Krzlwsxh))
                    .ForMember(dest => dest.GuestHistoryId, opt => opt.MapFrom(src => src.Krzllsxh))
                    .ForMember(dest => dest.InvoiceAmount, opt => opt.MapFrom(src => src.Krzlfpje))
                    .ForMember(dest => dest.InvoiceCode, opt => opt.MapFrom(src => src.Krzlfphm))
                    .ForMember(dest => dest.InvoiceCount, opt => opt.MapFrom(src => src.Krzlfpsl))
                    .ForMember(dest => dest.LastTimeAmount, opt => opt.MapFrom(src => src.Krzlsrye))
                    .ForMember(dest => dest.OriginCheckInDate, opt => opt.MapFrom(src => src.Krzlyrzr))
                    .ForMember(dest => dest.OriginCheckOutDate, opt => opt.MapFrom(src => src.Krzlyldr))
                    .ForMember(dest => dest.Phone01, opt => opt.MapFrom(src => src.Krzldh01))
                    .ForMember(dest => dest.RoomBreakfast, opt => opt.MapFrom(src => src.Krzlfjsx))
                    .ForMember(dest => dest.RoomChuangeDate, opt => opt.MapFrom(src => src.Krzlhfrq))
                    .ForMember(dest => dest.RoomChuangeNo, opt => opt.MapFrom(src => src.Krzlhffh))
                    .ForMember(dest => dest.RoomPriceStructure, opt => opt.MapFrom(src => src.Krzlfjjg))
                    .ForMember(dest => dest.SubReceiptCode, opt => opt.MapFrom(src => src.Krzlfddm))
                    //.ForMember(dest => dest, opt => opt.MapFrom(src => src))
                    .ReverseMap(); 
            #endregion

            #region 客人账务对象映射
            CreateMap<KrzwModel, GuestAccountingInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccId01, opt => opt.MapFrom(src => src.Krzwxh01))
                    .ForMember(dest => dest.AccId02, opt => opt.MapFrom(src => src.Krzwxh02))
                    .ForMember(dest => dest.AccId03, opt => opt.MapFrom(src => src.Krzwxh03))
                    .ForMember(dest => dest.AccountingCode, opt => opt.MapFrom(src => src.Krzwzwdm))
                    .ForMember(dest => dest.AccountingDate, opt => opt.MapFrom(src => src.Krzwzwrq))
                    .ForMember(dest => dest.AccountingType, opt => opt.MapFrom(src => src.Krzwlx00))
                    .ForMember(dest => dest.BillType, opt => opt.MapFrom(src => src.Krzwjdxz))
                    .ForMember(dest => dest.CalculateAmount, opt => opt.MapFrom(src => src.Krzwhsje))
                    .ForMember(dest => dest.ChildId, opt => opt.MapFrom(src => src.Krzwfzh0))
                    .ForMember(dest => dest.ConsumeAmount, opt => opt.MapFrom(src => src.Krzwxfje))
                    .ForMember(dest => dest.CurrencyType, opt => opt.MapFrom(src => src.Krzwfkhb))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Krzwzh00))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Krzwczsj))
                    .ForMember(dest => dest.Operation, opt => opt.MapFrom(src => src.Krzwczcz))
                    .ForMember(dest => dest.PayableAmount, opt => opt.MapFrom(src => src.Krzwyfje))
                    .ForMember(dest => dest.PaymentMethod, opt => opt.MapFrom(src => src.Krzwfkfs))
                    .ForMember(dest => dest.ReferenceNo, opt => opt.MapFrom(src => src.Krzwckhm))
                    .ForMember(dest => dest.RelationId, opt => opt.MapFrom(src => src.Krzwgrzh))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Krzwbz00))
                    .ForMember(dest => dest.Shift, opt => opt.MapFrom(src => src.Krzwbc00))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Krzwztbz))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Krzwczdm))
                    //.ForMember(dest => dest, opt => opt.MapFrom(src => src))
                    .ReverseMap(); //反向映射 
            #endregion


            #region 账务代码对象映射
            CreateMap<ZwdmModel, AccountingCodeInfo>()
                    .ForMember(dest => dest.AccCode, opt => opt.MapFrom(src => src.Id.Trim()))
                    .ForMember(dest => dest.AccCategory, opt => opt.MapFrom(src => src.Zwdmzwlb))
                    .ForMember(dest => dest.AccName, opt => opt.MapFrom(src => src.Zwdmmc00))
                    .ForMember(dest => dest.AccProperty, opt => opt.MapFrom(src => src.Zwdmattr))
                    .ForMember(dest => dest.AccReceivableCode, opt => opt.MapFrom(src => src.Zwdmysdm))
                    .ForMember(dest => dest.BillType, opt => opt.MapFrom(src => src.Zwdmjdxz))
                    .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Zwdmlb00))
                    .ForMember(dest => dest.EnglishName, opt => opt.MapFrom(src => src.Zwdmywmc))
                    .ForMember(dest => dest.ParentCode, opt => opt.MapFrom(src => src.Zwdmsslb))
                    .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Zwdmdj00))
                    .ForMember(dest => dest.ReferenceNo, opt => opt.MapFrom(src => src.Zwdmckhm))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Zwdmbz00))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Zwdmbzs0))
                    .ForMember(dest => dest.SubId, opt => opt.MapFrom(src => src.Zwdmfzh0))
                    .ForMember(dest => dest.Unit, opt => opt.MapFrom(src => src.Zwdmdw00))
                    .ReverseMap(); 
            #endregion

            #region AR账（应收账）对象映射
            CreateMap<Arz0Model, AccountReceivableInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.CancelTime, opt => opt.MapFrom(src => src.Arz0cxsj))
                    .ForMember(dest => dest.CancelUser, opt => opt.MapFrom(src => src.Arz0cxcz))
                    .ForMember(dest => dest.GuestAccId, opt => opt.MapFrom(src => src.Arz0zwxh))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Arz0czsj))
                    .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Arz0lx00))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Arz0czdm))
                    .ReverseMap(); 
            #endregion

            #region 订房明细对象映射
            CreateMap<DfmxModel, BookingDetailInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.ActualStayRoomNum, opt => opt.MapFrom(src => src.Dfmxrz00))
                    .ForMember(dest => dest.BookingDate, opt => opt.MapFrom(src => src.Dfmxydrq))
                    .ForMember(dest => dest.BookingId, opt => opt.MapFrom(src => src.Dfmxydh0))
                    .ForMember(dest => dest.CancelDate, opt => opt.MapFrom(src => src.Dfmxqxrq))
                    .ForMember(dest => dest.CancelRoomNum, opt => opt.MapFrom(src => src.Dfmxqx00))
                    .ForMember(dest => dest.CheckInDate, opt => opt.MapFrom(src => src.Dfmxrzrq))
                    .ForMember(dest => dest.CheckOutDate, opt => opt.MapFrom(src => src.Dfmxldrq))
                    .ForMember(dest => dest.ConfirmRoomNum, opt => opt.MapFrom(src => src.Dfmxqr00))
                    .ForMember(dest => dest.ExpiredDate, opt => opt.MapFrom(src => src.Dfmxsxrq))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Dfmxczsj))
                    .ForMember(dest => dest.PeopleNum, opt => opt.MapFrom(src => src.Dfmxrs00))
                    .ForMember(dest => dest.RoomNum, opt => opt.MapFrom(src => src.Dfmxfs00))
                    .ForMember(dest => dest.RoomPrice, opt => opt.MapFrom(src => src.Dfmxfj00))
                    .ForMember(dest => dest.RoomPriceCategory, opt => opt.MapFrom(src => src.Dfmxfjlb.Trim()))
                    .ForMember(dest => dest.RoomProperty, opt => opt.MapFrom(src => src.Dfmxfjsx))
                    .ForMember(dest => dest.RoomType, opt => opt.MapFrom(src => src.Dfmxfl00.Trim()))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Dfmxzt00))
                    .ForMember(dest => dest.UpGradeId, opt => opt.MapFrom(src => src.Dfmxsjxh))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Dfmxczdm))
                    .ReverseMap(); 
            #endregion

            #region 订房资料对象映射
            CreateMap<DfzlModel, BookingInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccRemark, opt => opt.MapFrom(src => src.Dfzlzwbz))
                    .ForMember(dest => dest.BookingCategory, opt => opt.MapFrom(src => src.Dfzllb00))
                    .ForMember(dest => dest.BookingDate, opt => opt.MapFrom(src => src.Dfzlydrq))
                    .ForMember(dest => dest.BookingRemark, opt => opt.MapFrom(src => src.Dfzldfbz))
                    .ForMember(dest => dest.ChargeLimitAmount, opt => opt.MapFrom(src => src.Dfzlgzxe))
                    .ForMember(dest => dest.CheckInDate, opt => opt.MapFrom(src => src.Dfzlrzrq))
                    .ForMember(dest => dest.CheckInTime, opt => opt.MapFrom(src => src.Dfzlrzsj))
                    .ForMember(dest => dest.CheckOutDate, opt => opt.MapFrom(src => src.Dfzlldrq))
                    .ForMember(dest => dest.CheckOutTime, opt => opt.MapFrom(src => src.Dfzlldsj))
                    .ForMember(dest => dest.ClientSourceCode, opt => opt.MapFrom(src => src.Dfzlscdm))
                    .ForMember(dest => dest.ClientType, opt => opt.MapFrom(src => src.Dfzllxdm))
                    .ForMember(dest => dest.CommisionCode, opt => opt.MapFrom(src => src.Dfzlyjdm))
                    .ForMember(dest => dest.ContactRemark, opt => opt.MapFrom(src => src.Dfzllxbz))
                    .ForMember(dest => dest.Contacts, opt => opt.MapFrom(src => src.Dfzllxr0))
                    .ForMember(dest => dest.CountryCode, opt => opt.MapFrom(src => src.Dfzlgj00))
                    .ForMember(dest => dest.Currency, opt => opt.MapFrom(src => src.Dfzljzhb))
                    .ForMember(dest => dest.EstimateNum, opt => opt.MapFrom(src => src.Dfzlyjrs))
                    .ForMember(dest => dest.ExpiredDate, opt => opt.MapFrom(src => src.Dfzlsxrq))
                    .ForMember(dest => dest.GuestCategory, opt => opt.MapFrom(src => src.Dfzlkrlb))
                    .ForMember(dest => dest.GuestRemark, opt => opt.MapFrom(src => src.Dfzlkrbz))
                    .ForMember(dest => dest.PayBillMethod, opt => opt.MapFrom(src => src.Dfzljzfs))
                    .ForMember(dest => dest.PeopleNum, opt => opt.MapFrom(src => src.Dfzlrs00))
                    .ForMember(dest => dest.RoomBreakfast, opt => opt.MapFrom(src => src.Dfzlfjsx))
                    .ForMember(dest => dest.RoomNum, opt => opt.MapFrom(src => src.Dfzlfs00))
                    .ForMember(dest => dest.RoomPriceCategory, opt => opt.MapFrom(src => src.Dfzlfjlb))
                    .ForMember(dest => dest.RoomPriceStructure, opt => opt.MapFrom(src => src.Dfzlfjjg))
                    .ForMember(dest => dest.SellerCode, opt => opt.MapFrom(src => src.Dfzlywy0))
                    .ForMember(dest => dest.SpecialRemark, opt => opt.MapFrom(src => src.Dfzlydbz))
                    .ForMember(dest => dest.SpecialServices, opt => opt.MapFrom(src => src.Dfzltf00))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Dfzlzt00))
                    .ForMember(dest => dest.SubReceiptCode, opt => opt.MapFrom(src => src.Dfzlfddm))
                    .ForMember(dest => dest.TeamName, opt => opt.MapFrom(src => src.Dfzltm00))
                    .ForMember(dest => dest.TeamNo, opt => opt.MapFrom(src => src.Dfzlth00))
                    .ForMember(dest => dest.VerifyFlag, opt => opt.MapFrom(src => src.Dfzlshbz))
                    .ForMember(dest => dest.VipType, opt => opt.MapFrom(src => src.Dfzlvip0))
                    //.ForMember(dest => dest, opt => opt.MapFrom(src => src))
                    .ReverseMap(); 
            #endregion

            #region 清洁分配对象映射
            CreateMap<QjfpModel, CleanDistributionInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccDate, opt => opt.MapFrom(src => src.Qjfpzwrq))
                    .ForMember(dest => dest.CancelTime, opt => opt.MapFrom(src => src.Qjfpcxsj))
                    .ForMember(dest => dest.CancelUser, opt => opt.MapFrom(src => src.Qjfpcxcz))
                    .ForMember(dest => dest.CleanTime, opt => opt.MapFrom(src => src.Qjfpqjsj))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Qjfpfpsj))
                    .ForMember(dest => dest.RoomNo, opt => opt.MapFrom(src => src.Qjfpfhdm))
                    .ForMember(dest => dest.ServerCode, opt => opt.MapFrom(src => src.Qjfpfwry))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Qjfpzt00))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Qjfpfpcz))
                    .ReverseMap(); 
            #endregion

            #region 清洁签到对象映射
            CreateMap<QjbdModel, CleanSigninInfo>()
                   .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                   .ForMember(dest => dest.AccDate, opt => opt.MapFrom(src => src.Qjbdzwrq))
                   .ForMember(dest => dest.CancelTime, opt => opt.MapFrom(src => src.Qjbdcxsj))
                   .ForMember(dest => dest.CancelUser, opt => opt.MapFrom(src => src.Qjbdcxcz))
                   .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Qjbdczsj))
                   .ForMember(dest => dest.ServerCode, opt => opt.MapFrom(src => src.Qjbdfwry))
                   .ForMember(dest => dest.SigninMethod, opt => opt.MapFrom(src => src.Qjbdbdfs))
                   .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Qjbdzt00))
                   .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Qjbdczdm))
                   .ReverseMap(); 
            #endregion

            #region 客人外事对象映射
            CreateMap<KrwsModel, ForeignGuestInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.EntryDate, opt => opt.MapFrom(src => src.Krwsrjrq))
                    .ForMember(dest => dest.EntryPort, opt => opt.MapFrom(src => src.Krwsrjka))
                    .ForMember(dest => dest.EntryReason, opt => opt.MapFrom(src => src.Krwsrjsy))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Krwszh00))
                    .ForMember(dest => dest.IssuedBy, opt => opt.MapFrom(src => src.Krwsqfdw))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Krwsbz00))
                    .ForMember(dest => dest.VisaCategory, opt => opt.MapFrom(src => src.Krwsqzlb))
                    .ForMember(dest => dest.VisaEffectiveDate, opt => opt.MapFrom(src => src.Krwsqzyx))
                    .ForMember(dest => dest.VisaNo, opt => opt.MapFrom(src => src.Krwsqzzh))
                    .ReverseMap(); 
            #endregion

            #region 客人发卡对象映射
            CreateMap<KrfkModel, GuestCardInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.CancelByUser, opt => opt.MapFrom(src => src.Krfksxcz))
                    .ForMember(dest => dest.CardDate, opt => opt.MapFrom(src => src.Krfkrq00))
                    .ForMember(dest => dest.CardId, opt => opt.MapFrom(src => src.Krfkkhid))
                    .ForMember(dest => dest.CardNo, opt => opt.MapFrom(src => src.Krfkkh00))
                    .ForMember(dest => dest.CardState, opt => opt.MapFrom(src => src.Krfkbzs0))
                    .ForMember(dest => dest.ExpiredDate, opt => opt.MapFrom(src => src.Krfksxrq))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Krfkkrzh))
                    .ForMember(dest => dest.GuestName, opt => opt.MapFrom(src => src.Krfkxm00))
                    .ForMember(dest => dest.PostDate, opt => opt.MapFrom(src => src.Krfkjzrq))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Krfkbz00))
                    .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.Krfkksrq))
                    .ForMember(dest => dest.Types, opt => opt.MapFrom(src => src.Krfklx00))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Krfkczdm))
                    .ReverseMap(); 
            #endregion

            #region 客人消费对象映射
            CreateMap<KrxfModel, GuestConsumeInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccDate, opt => opt.MapFrom(src => src.Krxfzwrq))
                    .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Krxfje00))
                    .ForMember(dest => dest.CardId, opt => opt.MapFrom(src => src.Krxfkhid))
                    .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Krxflb00))
                    .ForMember(dest => dest.ConsumePlace, opt => opt.MapFrom(src => src.Krxfxfd0))
                    .ForMember(dest => dest.FreeFlag, opt => opt.MapFrom(src => src.Krxfzsbz))
                    .ForMember(dest => dest.MainCardId, opt => opt.MapFrom(src => src.Krxfzkxh))
                    .ForMember(dest => dest.OperateDate, opt => opt.MapFrom(src => src.Krxfrq00))
                    .ForMember(dest => dest.PaymentMethod, opt => opt.MapFrom(src => src.Krxffkfs))
                    .ForMember(dest => dest.PropertyValue, opt => opt.MapFrom(src => src.Krxfattr))
                    .ForMember(dest => dest.RemainAmount, opt => opt.MapFrom(src => src.Krxfye00))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Krxfbz00))
                    .ForMember(dest => dest.SubId, opt => opt.MapFrom(src => src.Krxfzh00))
                    .ForMember(dest => dest.Times, opt => opt.MapFrom(src => src.Krxfje01))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Krxfczdm))
                    .ReverseMap(); 
            #endregion

            #region 客人历史对象映射
            CreateMap<KrlsModel, GuestHistoryInfo>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(dest => dest.Address, opt => opt.MapFrom(src => src.Krlsdz00))
                .ForMember(dest => dest.BirthDate, opt => opt.MapFrom(src => src.Krlscsrq))
                .ForMember(dest => dest.CardId, opt => opt.MapFrom(src => src.Krlskhid))
                .ForMember(dest => dest.CardIssuer, opt => opt.MapFrom(src => src.Krlsfkr0))
                .ForMember(dest => dest.CardNo01, opt => opt.MapFrom(src => src.Krlskh01))
                .ForMember(dest => dest.ClientType, opt => opt.MapFrom(src => src.Krlslxdm))
                .ForMember(dest => dest.ChargeLimitAmount, opt => opt.MapFrom(src => src.Krlsgzxe))
                .ForMember(dest => dest.ChargeLimitTotalAmount, opt => opt.MapFrom(src => src.Krlsgzze))
                .ForMember(dest => dest.ChineseName, opt => opt.MapFrom(src => src.Krlszwxm))
                .ForMember(dest => dest.Company, opt => opt.MapFrom(src => src.Krlsdw00))
                .ForMember(dest => dest.ConsumeAmount, opt => opt.MapFrom(src => src.Krlsxfze))
                .ForMember(dest => dest.CountryCode, opt => opt.MapFrom(src => src.Krlsgj00))
                .ForMember(dest => dest.CredentialCategory, opt => opt.MapFrom(src => src.Krlszjlb))
                .ForMember(dest => dest.CredentialNo, opt => opt.MapFrom(src => src.Krlszjhm))
                .ForMember(dest => dest.DiscountFlag, opt => opt.MapFrom(src => src.Krlsyhbz))
                .ForMember(dest => dest.DiscountNo, opt => opt.MapFrom(src => src.Krlsyhzh))
                .ForMember(dest => dest.EffectiveDate, opt => opt.MapFrom(src => src.Krlsyxrq))
                .ForMember(dest => dest.Email, opt => opt.MapFrom(src => src.Krlsmail))
                .ForMember(dest => dest.EnglishName, opt => opt.MapFrom(src => src.Krlsywxm))
                .ForMember(dest => dest.Fax, opt => opt.MapFrom(src => src.Krlsfax0))
                .ForMember(dest => dest.FirstCheckInDate, opt => opt.MapFrom(src => src.Krlsscrz))
                .ForMember(dest => dest.FirstCheckInTime, opt => opt.MapFrom(src => src.Krlsdyrz))
                .ForMember(dest => dest.FirstCheckOutDate, opt => opt.MapFrom(src => src.Krlsscld))
                .ForMember(dest => dest.FirstDiscount, opt => opt.MapFrom(src => src.Krlsscyh))
                .ForMember(dest => dest.FirstPriceCategory, opt => opt.MapFrom(src => src.Krlsscjl))
                .ForMember(dest => dest.FirstRoomNo, opt => opt.MapFrom(src => src.Krlsscfh))
                .ForMember(dest => dest.FirstRoomPrice, opt => opt.MapFrom(src => src.Krlsscfj))
                .ForMember(dest => dest.FirstRoomType, opt => opt.MapFrom(src => src.Krlsscfl))
                .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Krlsxb00))
                .ForMember(dest => dest.GuestPwd, opt => opt.MapFrom(src => src.Krlsmm00))
                .ForMember(dest => dest.GuestType, opt => opt.MapFrom(src => src.Krlskrlx))
                .ForMember(dest => dest.ICDate, opt => opt.MapFrom(src => src.Krlsfkrq))
                .ForMember(dest => dest.LoginId, opt => opt.MapFrom(src => src.Krlsdlid))
                .ForMember(dest => dest.NativePlace, opt => opt.MapFrom(src => src.Krlsjg00))
                .ForMember(dest => dest.OtherAmount, opt => opt.MapFrom(src => src.Krlsqtze))
                .ForMember(dest => dest.OtherPayment, opt => opt.MapFrom(src => src.Krlsqtfk))
                .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Krlsdh00))
                .ForMember(dest => dest.Photo, opt => opt.MapFrom(src => src.Krlsxp00))
                .ForMember(dest => dest.PointRemainAmount, opt => opt.MapFrom(src => src.Krlsje01)) //?
                .ForMember(dest => dest.PointTotalAmount, opt => opt.MapFrom(src => src.Krlsjfze)) //?
                .ForMember(dest => dest.RemainAmount, opt => opt.MapFrom(src => src.Krlsye00))
                .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Krlsbz00))
                .ForMember(dest => dest.Remark01, opt => opt.MapFrom(src => src.Krlsbz01))
                .ForMember(dest => dest.Remark02, opt => opt.MapFrom(src => src.Krlsbz02))
                .ForMember(dest => dest.Remark03, opt => opt.MapFrom(src => src.Krlsbz03))
                .ForMember(dest => dest.RestaurantAmount, opt => opt.MapFrom(src => src.Krlscyze))
                .ForMember(dest => dest.RestaurantFlag, opt => opt.MapFrom(src => src.krlxcybz))
                .ForMember(dest => dest.RoomCheckIns, opt => opt.MapFrom(src => src.Krlszdcs))
                .ForMember(dest => dest.RoomDays, opt => opt.MapFrom(src => src.Krlszdts))
                .ForMember(dest => dest.RoomFlag, opt => opt.MapFrom(src => src.krlxkfbz))
                .ForMember(dest => dest.RoomRentAmount, opt => opt.MapFrom(src => src.Krlsfzze))
                .ForMember(dest => dest.SignImage, opt => opt.MapFrom(src => src.Krlsqm00))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Krlszt00))
                .ForMember(dest => dest.VipCardNo, opt => opt.MapFrom(src => src.Krlsvpkh))
                .ForMember(dest => dest.VipType, opt => opt.MapFrom(src => src.Krlsvip0))
                .ReverseMap();
            #endregion

            #region 客人留言对象映射
            CreateMap<KrlyModel, GuestMsgInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.CancelByUser, opt => opt.MapFrom(src => src.Krlyqxcz))
                    .ForMember(dest => dest.CancelDate, opt => opt.MapFrom(src => src.Krlysxrq))
                    .ForMember(dest => dest.CancelTime, opt => opt.MapFrom(src => src.Krlyqxsj))
                    .ForMember(dest => dest.Contents, opt => opt.MapFrom(src => src.Krlytext))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Krlyzh00))
                    .ForMember(dest => dest.MsgState, opt => opt.MapFrom(src => src.Krlyzt00))
                    .ForMember(dest => dest.MsgTopic, opt => opt.MapFrom(src => src.Krlybt00))
                    .ForMember(dest => dest.MsgType, opt => opt.MapFrom(src => src.Krlylx00))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Krlyczsj))
                    .ForMember(dest => dest.PermissionRemark, opt => opt.MapFrom(src => src.Krlyqxbz))
                    .ForMember(dest => dest.ReadUsers, opt => opt.MapFrom(src => src.Krlyyd00))
                    .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.Krlyksrq))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Krlyczdm))
                    .ReverseMap();
            #endregion

            #region 客人住店对象映射
            CreateMap<KrzdModel, GuestRoomDailyInfo>()
                    .ForMember(dest => dest.Date, opt => opt.MapFrom(src => src.Krzdrq00))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Krzdzh00))
                    .ForMember(dest => dest.AccountType, opt => opt.MapFrom(src => src.Krzdzhlx))
                    .ForMember(dest => dest.AccRemark, opt => opt.MapFrom(src => src.Krzdzwbz))
                    .ForMember(dest => dest.BookingDetailId, opt => opt.MapFrom(src => src.KrzdDfmx))
                    .ForMember(dest => dest.BookingId, opt => opt.MapFrom(src => src.Krzdydh0))
                    .ForMember(dest => dest.BookingTpye, opt => opt.MapFrom(src => src.Krzdydlb))
                    .ForMember(dest => dest.CardNo, opt => opt.MapFrom(src => src.Krzdkh00))
                    .ForMember(dest => dest.CheckInDate, opt => opt.MapFrom(src => src.Krzdrzrq))
                    .ForMember(dest => dest.CheckOutDate, opt => opt.MapFrom(src => src.Krzdldrq))
                    .ForMember(dest => dest.ChineseName, opt => opt.MapFrom(src => src.Krzdzwxm))
                    .ForMember(dest => dest.ChummageId, opt => opt.MapFrom(src => src.Krzdtzxh))
                    .ForMember(dest => dest.ClientType, opt => opt.MapFrom(src => src.Krzdlxdm))
                    .ForMember(dest => dest.ConsumeAmount, opt => opt.MapFrom(src => src.Krzdxfze))
                    .ForMember(dest => dest.EnglishName, opt => opt.MapFrom(src => src.Krzdywxm))
                    .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Krzdxb00))
                    .ForMember(dest => dest.GuestCategory, opt => opt.MapFrom(src => src.Krzdkrlb))
                    .ForMember(dest => dest.GuestRemark, opt => opt.MapFrom(src => src.Krzdkrbz))
                    .ForMember(dest => dest.GuestType, opt => opt.MapFrom(src => src.Krzdkrlx))
                    .ForMember(dest => dest.LastTimeAmount, opt => opt.MapFrom(src => src.Krzdsrye))
                    .ForMember(dest => dest.PayBillId, opt => opt.MapFrom(src => src.Krzdjzzh))
                    .ForMember(dest => dest.RemainAmount, opt => opt.MapFrom(src => src.Krzdye00))
                    .ForMember(dest => dest.RoomBreakfast, opt => opt.MapFrom(src => src.Krzdfjsx))
                    .ForMember(dest => dest.RoomNo, opt => opt.MapFrom(src => src.Krzdfh00))
                    .ForMember(dest => dest.RoomPriceCategory, opt => opt.MapFrom(src => src.Krzdfjlb))
                    .ForMember(dest => dest.RoomPriceStructure, opt => opt.MapFrom(src => src.Krzdfjjg))
                    .ForMember(dest => dest.RoomRent, opt => opt.MapFrom(src => src.Krzdfz00))
                    .ForMember(dest => dest.RoomType, opt => opt.MapFrom(src => src.Krzdfjlx))
                    .ForMember(dest => dest.SellerCode, opt => opt.MapFrom(src => src.Krzdywy0))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Krzdzt00))
                    .ForMember(dest => dest.TeamNo, opt => opt.MapFrom(src => src.Krzdth00))
                    .ForMember(dest => dest.VipType, opt => opt.MapFrom(src => src.Krzdvip0))
                    .ReverseMap();
            #endregion

            #region 客人事务对象映射
            CreateMap<KrswModel, GuestRoutineInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccDate, opt => opt.MapFrom(src => src.Krswzwrq))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Krswzh00))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Krswczsj))
                    .ForMember(dest => dest.OriginalContent, opt => opt.MapFrom(src => src.Krswysz0))
                    .ForMember(dest => dest.ReasonCode, opt => opt.MapFrom(src => src.Krswyydm))
                    .ForMember(dest => dest.RoutineCode, opt => opt.MapFrom(src => src.Krswswdm))
                    .ForMember(dest => dest.RoutineState, opt => opt.MapFrom(src => src.Krswbzs0))
                    .ForMember(dest => dest.UpdateContent, opt => opt.MapFrom(src => src.Krswgxz0))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Krswczdm))
                    .ReverseMap();
            #endregion

            #region 预授权对象映射
            CreateMap<Ysq0Model, PreAuthorizationInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccountId, opt => opt.MapFrom(src => src.Ysq0zh00))
                    .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Ysq0je00))
                    .ForMember(dest => dest.AuthNo, opt => opt.MapFrom(src => src.Ysq0sqh0))
                    .ForMember(dest => dest.CancelTime, opt => opt.MapFrom(src => src.Ysq0cxsj))
                    .ForMember(dest => dest.CancelUser, opt => opt.MapFrom(src => src.Ysq0cxdm))
                    .ForMember(dest => dest.CardNo, opt => opt.MapFrom(src => src.Ysq0kh00))
                    .ForMember(dest => dest.EffectiveDate, opt => opt.MapFrom(src => src.Ysq0yxq0))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Ysq0czsj))
                    .ForMember(dest => dest.PrintMsg, opt => opt.MapFrom(src => src.Ysq0msg0))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Ysq0bz00))
                    .ForMember(dest => dest.SearchCode, opt => opt.MapFrom(src => src.Ysq0cxm0))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Ysq0zt00))
                    .ForMember(dest => dest.TimeRemark, opt => opt.MapFrom(src => src.Ysq0cxm1))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Ysq0czdm))
                    .ReverseMap();
            #endregion

            #region 价格体系对象映射
            CreateMap<JgtxModel, PriceSystemInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.Category, opt => opt.MapFrom(src => src.Jgtxsslb))
                    .ForMember(dest => dest.Contents, opt => opt.MapFrom(src => src.Jgtxtext))
                    .ForMember(dest => dest.EndDate, opt => opt.MapFrom(src => src.Jgtxjsrq))
                    .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Jgtxmc00))
                    .ForMember(dest => dest.PeopleNum, opt => opt.MapFrom(src => src.Jgtxrs00))
                    .ForMember(dest => dest.SpecialDate, opt => opt.MapFrom(src => src.Jgtxtsrq))
                    .ForMember(dest => dest.StartDate, opt => opt.MapFrom(src => src.Jgtxksrq))
                    .ForMember(dest => dest.UseLevel, opt => opt.MapFrom(src => src.Jgtxyxjb))
                    .ForMember(dest => dest.Weeks, opt => opt.MapFrom(src => src.Jgtxxq00))
                    .ReverseMap();
            #endregion

            #region 应收明细对象映射
            CreateMap<YsmxModel, ReceivableDetailInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccReceivableCode, opt => opt.MapFrom(src => src.Ysmxysdm))
                    .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Ysmxje00))
                    .ForMember(dest => dest.BillType, opt => opt.MapFrom(src => src.Ysmxjdxz))
                    .ForMember(dest => dest.Days, opt => opt.MapFrom(src => src.Ysmxts00))
                    .ForMember(dest => dest.InvoiceCode, opt => opt.MapFrom(src => src.Ysmxfph0))
                    .ForMember(dest => dest.MainId, opt => opt.MapFrom(src => src.Ysmxzdxh))
                    .ForMember(dest => dest.Num, opt => opt.MapFrom(src => src.Ysmxsl00))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Ysmxczsj))
                    .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Ysmxdh00))
                    .ForMember(dest => dest.Price, opt => opt.MapFrom(src => src.Ysmxdj00))
                    .ForMember(dest => dest.Reason, opt => opt.MapFrom(src => src.Ysmxysyy))
                    .ForMember(dest => dest.ReceivableDate, opt => opt.MapFrom(src => src.Ysmxrq00))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Ysmxbz00))
                    .ForMember(dest => dest.Remark01, opt => opt.MapFrom(src => src.Ysmxbz01))
                    .ForMember(dest => dest.SubId, opt => opt.MapFrom(src => src.Ysmxfzh0))
                    .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Ysmxlx00))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Ysmxczdm))
                    .ReverseMap();
            #endregion

            #region 应收单对象映射
            CreateMap<Ysd0Model, ReceivableFormInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.CheckInDate, opt => opt.MapFrom(src => src.Ysd0rzrq))
                    .ForMember(dest => dest.CheckOutDate, opt => opt.MapFrom(src => src.Ysd0ldrq))
                    .ForMember(dest => dest.ClientType, opt => opt.MapFrom(src => src.Ysd0lxdm))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Ysd0krzh))
                    .ForMember(dest => dest.InvoiceNo, opt => opt.MapFrom(src => src.Ysd0fph0))
                    .ForMember(dest => dest.OtherAmount, opt => opt.MapFrom(src => src.Ysd0qtje))
                    .ForMember(dest => dest.PaidAmount, opt => opt.MapFrom(src => src.Ysd0yfje))
                    .ForMember(dest => dest.PeopleNum, opt => opt.MapFrom(src => src.Ysd0rs00))
                    .ForMember(dest => dest.PostDate, opt => opt.MapFrom(src => src.Ysd0jzrq))
                    .ForMember(dest => dest.PostRemark, opt => opt.MapFrom(src => src.Ysd0jzcz))
                    .ForMember(dest => dest.ReceivabelDate, opt => opt.MapFrom(src => src.Ysd0rq00))
                    .ForMember(dest => dest.ReceivableAmount, opt => opt.MapFrom(src => src.Ysd0ysje))
                    .ForMember(dest => dest.RemainAmount, opt => opt.MapFrom(src => src.Ysd0ye00))
                    .ForMember(dest => dest.Remark, opt => opt.MapFrom(src => src.Ysd0bz00))
                    .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Ysd0bzs0))
                    .ForMember(dest => dest.TeamName, opt => opt.MapFrom(src => src.Ysd0tm00))
                    .ForMember(dest => dest.TeamNo, opt => opt.MapFrom(src => src.Ysd0th00))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Ysd0czdm))
                    .ReverseMap();
            #endregion

            #region 房间物品对象映射
            CreateMap<FjwpModel, RoomGoodsInfo>()
                    .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
                    .ForMember(dest => dest.AccDate, opt => opt.MapFrom(src => src.Fjwpzwrq))
                    .ForMember(dest => dest.GoodsCode, opt => opt.MapFrom(src => src.Fjwpdm00))
                    .ForMember(dest => dest.GuestId, opt => opt.MapFrom(src => src.Fjwpzh00))
                    .ForMember(dest => dest.Num, opt => opt.MapFrom(src => src.Fjwpsl00))
                    .ForMember(dest => dest.OperateTime, opt => opt.MapFrom(src => src.Fjwpczsj))
                    .ForMember(dest => dest.RoomNo, opt => opt.MapFrom(src => src.Fjwpfhdm))
                    .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Fjwplx00))
                    .ForMember(dest => dest.UserCode, opt => opt.MapFrom(src => src.Fjwpczdm))
                    .ReverseMap(); 
            #endregion

        }
    }
}
